### configuration file for openfortivpn, see man openfortivpn(1) ###
# this goes in /etc/openfortivpn

# host = vpn.example.org
# port = 443
# username = vpnuser
# password = VPNpassw0rd
#
host = guestid.cuvpn.cornell.edu
port = 443
username = gid-michelsl@AG-PBG-USDA-WheatCap-Guests
password = --- recdacted ---
realm = AG-PBG-USDA-WheatCap-Guests

